version: "3.9"  # optional since v1.27.0

services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/test  -user=test -password=test -connectRetries=3 migrate
    volumes:
      - ./flyway:/flyway/sql
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    ports:
      - '5432:5432'