spring:
  quartz:
    job-store-type: memory
  datasource:
    driver-class-name: org.postgresql.Driver
    username: test
    url: jdbc:postgresql://localhost:5432/test
    password: test

org:
  quartz:
    jobStore:
      class: org.quartz.simpl.RAMJobStore

contract:
  node-url: "https://data-seed-prebsc-1-s1.binance.org:8545/"
  private-key: "****"
  address: "0x05178F13Ee9a5Ae1A8478f5730f260a34A238d82"